### ISSUE TITLE
EventDispatcher.lua:56: GameTooltip doesn't have a "OnTooltipSetItem" script

### ISSUE THREAD

**Issue by Ookami313** [kemayo/wow-doesmyaltknowthat#2]
Testing addons to see what was working and what wasn't for DF. Enabled v7 and I'm receiving the following error after reloading. Thanks.

2x ...ddOns/DoesMyAltKnowThat/template/EventDispatcher.lua:56: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@DoesMyAltKnowThat/template/EventDispatcher.lua"]:56: in function `HookScript'
[string "@DoesMyAltKnowThat/core.lua"]:35: in function `?'
[string "@DoesMyAltKnowThat/template/Module.lua"]:40: in function `ModCall'
[string "@DoesMyAltKnowThat/template/Module.lua"]:48: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DoesMyAltKnowThat/template/EventDispatcher.lua"]:19: in function <...ddOns/DoesMyAltKnowThat/template/EventDispatcher.lua:18>

**Comment by kemayo** [comment]
Oops, I fixed that back in 6453ac7cb224c1bab172305717fa992790ec558b but didn't push a release out. I will fix that.
